### ISSUE TITLE
Version 1.3 Alarms don't save and crash Artisan

### ISSUE THREAD

**Issue by DavidFW1960** [artisan-roaster-scope/artisan#182] opened 2018-04-18 00:23 UTC
## Expected Behavior
Alarms should be able to be saved after editing Temperature

## Actual Behavior
Pressing save crashes software and does not save alarm

## Steps to Reproduce the Problem
Open Alarms and edit a Temperature and press save
  1.Open Alarms
  2.Enter or Edit a Temperature
  3.Save

## Specifications

  - Artisan Version: 1.3.0
  - Artisan Build (number in brackets shown in the about box):ca3c5f1
  - Platform (Mac/Windows/Linux + OS version):Linux, Raspbian Stretch
  - Connected devices or roasting machine: Hottop but not relevant
  
Please attach your current Artisan settings file (as exported via menu Help >> Save Setings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.
Saving Settings also caused a crash just now.
I zipped a settings and alarm file. It had a bz2 extension but i renamed it to zip as I could not uppload it otherwise.

[profile.zip](https://github.com/artisan-roaster-scope/artisan/files/1922030/profile.zip)

**Comment by rpaulo** [comment] 2018-04-18 05:26
When it crashes, can you show us what are the crash details?

**Comment by DavidFW1960** [comment] 2018-05-08 10:02
It’s not a permissions error.
You don’t sumo in the GUI.
This worked perfectly in 1.2 and I can manually edit the alarm file.

**Comment by DavidFW1960** [comment] 2018-05-08 10:05
It’s not a permissions error.
You don’t sudo in the GUI.
This worked perfectly in 1.2 and I can manually edit the alarm file.

**Comment by MAKOMO** [comment] 2018-05-08 13:34
v1.2 was build on a totally different stack still using Python2 and Qt4. v1.3 runs on Python3 and Qt5. 
The v1.3 builds seem to have an issue opening a file selector on some hardware/software combinations (not on mine!?). See also Issue #188 and Issue #187. Could you please run the following two commands and post the results here?

```
# cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

```
# cat /proc/cpuinfo | grep 'Revision' | awk '{print $3}' | sed 's/^1000//'
a22082
```

**Comment by DavidFW1960** [comment] 2018-05-09 01:26
pi@piv3-spare:~$ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
pi@piv3-spare:~$ cat /proc/cpuinfo | grep 'Revision' | awk '{print $3}' | sed 's/^1000//'
a02082
pi@piv3-spare:~$

**Comment by DavidFW1960** [comment] 2018-05-09 01:38
ok it seems it might be settings if I load as sudo from terminal I don't get an error.

On the desktop I can right click on Artisan Icon and select properties. I can see the following:

![image](https://user-images.githubusercontent.com/36390762/39791147-611a458e-537d-11e8-9c23-817f2a36f667.png)

Wonder if I should change those for execute to anybody and change content to anybody as well?

**Comment by DavidFW1960** [comment] 2018-05-09 01:47
as per post in the crash thread from @samtsai5212 this fixes it permanently:

Artisan 1.3 crashes probably because it tried to save something without permission. Try to run Artisan in terminal with root privilege:
sudo artisan

If you want to make it permanent, run the following:
sudo nano /usr/share/applications/artisan.desktop
find the line:
Exec=artisan %U
Change to:
Exec=sudo artisan %U
press ctrl+X then
press Y then enter

**Comment by rpaulo** [comment] 2018-05-09 03:07
Can you find out which file Artisan is trying to save? Maybe strace will help.

**Comment by DavidFW1960** [comment] 2018-05-09 03:17
?? It's the alarm file that I was editing.

**Comment by rpaulo** [comment] 2018-05-09 05:54
If it was a permissions problem saving the alarms, we would see an exception and it would be handled by our exception handler, but in this case it looks like the software aborts.

**Comment by DavidFW1960** [comment] 2018-05-09 06:15
Yes exactly - crashes out to the desktop with no error.

**Comment by MAKOMO** [comment] 2018-05-09 07:35
The issue seems to be caused by a file access that files on opening a file selector with in the GUI libs of the underlying QT. This might be caused by a missing lib file in the Artisan RPi bundle and thus be a build issue. Running Artisan as root is a valid workaround for now, while I don't understand yet why this works. We are investigating...

**Comment by DavidFW1960** [comment] 2018-05-09 08:01
Thanks @MAKOMO Much appreciated

**Comment by MAKOMO** [comment] 2018-05-13 17:13
I close this one as it seems to have the same cause then Issue #187

**Closed by MAKOMO** 2018-05-13 17:13 UTC
Labels: RPi

**Comment by DavidFW1960** [comment] 2018-05-20 23:50
This looks ok now in 1.3.1 and also I note that installing 1.3.1 removed the sudo I added to the command in  /usr/share/applications/artisan.desktop

Thanks!

**Comment by MAKOMO** [comment] 2018-05-21 08:09
Thanks for double checking David!
