### ISSUE TITLE
In 1.6.1 cannot edit roast properties event times?

### ISSUE THREAD

**Issue by clarsen** [artisan-roaster-scope/artisan#334] opened 2019-03-16 19:43 UTC
## Expected Behavior
Used to be able to adjust event time, e.g. FC start or drop in the roast profile during or after a roast.

## Actual Behavior
UI will not accept edits to event times.

## Steps to Reproduce the Problem

  1. Bring up roast properties of any previous roast
  2. Go to events tab
  3. select time in event field, e.g. FC START
  4. try to replace time with new value

## Specifications

  - Artisan Version: 1.6.1
  - Artisan Build (number in brackets shown in the about box): c23da46
  - Platform (Mac/Windows/Linux + OS version): Raspberry PI Raspbian 9.6 (stretch)
  - Connected devices or roasting machine: Freshroast SR700
  
Please attach your current Artisan settings file (as exported via menu Help >> Save Setings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

[artisan-settings-1.6.1case.aset.txt](https://github.com/artisan-roaster-scope/artisan/files/2974419/artisan-settings-1.6.1case.aset.txt)
[Sumatra 3_19-03-16_1210.alog.txt](https://github.com/artisan-roaster-scope/artisan/files/2974422/Sumatra.3_19-03-16_1210.alog.txt)

**Comment by MAKOMO** [comment] 2019-03-16 20:18
Duplicate of #333 

This is a confirmed bug and is resolved in source. Next version will come with the fix. Until the new version is out this summer you can set/reset events using the right-click-to-BT popup which is also easier and faster to re-set events. Thanks for reporting and sorry. Beta builds with this fix are on BinTray https://bintray.com/artisan/artisan-artifacts/artisan/master#files

**Closed by MAKOMO** 2019-03-16 20:18 UTC
