### ISSUE TITLE
Missing Data - Roast Ranking report (Excel)

### ISSUE THREAD

**Issue by DennieSch** [artisan-roaster-scope/artisan#442] opened 2019-12-08 23:57 UTC
## Expected Behavior
When generating a Ranking Report (Excel), all applicable roast data is exported.
The issue seems to only occur with just one of my .alog files. 

## Actual Behavior
The data for DROP, DROP (F), DRY, MAI, DEV, AUC and Loss are missing (for this particular roast - number 111). 

However, this data IS present in a Web version of the Ranking Report.

Not sure if the problem is with the .alog (or not) since the Web version seems to work fine.

See attached

[Roast Ranking - Issue with Batch 111.zip](https://github.com/artisan-roaster-scope/artisan/files/3937332/Roast.Ranking.-.Issue.with.Batch.111.zip)

## Steps to Reproduce the Problem

  1. Report|Ranking|Excel (and Web)
  2. Select 3 .alog files
  3. Generate report(s)

## Specifications

version = 2.1.2 (98288e1e)
Architecture = ('64bit', 'WindowsPE')
Machine = AMD64
Platform name = Windows-10-10.0.18362-SP0
Processor = Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
Python Branch = tags/v3.7.5
Python Build = ('tags/v3.7.5:5c02a39a0b', 'Oct 15 2019 00:11:34')
Python Compiler = MSC v.1916 64 bit (AMD64)
Python Implementation = CPython
Python Revision = 5c02a39a0b
Python version = 3.7.5
Release = 10
System = Windows
Version = 10.0.18362
Win32 = ('10', '10.0.18362', 'SP0', '')

  - Connected devices or roasting machine: Phidget TMP1101
  
Please attach your current Artisan settings file (as exported via menu Help >> Save Setings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

**Comment by MAKOMO** [comment] 2019-12-09 13:39
A border case caused by rounding resolved by commit a02227689443df7b20d7e04e7f54f7bab854ecbc

**Closed by MAKOMO** 2019-12-09 13:39 UTC
