### ISSUE TITLE
Save Graph unable to save pdf file

### ISSUE THREAD

**Issue by Numberbuster** [artisan-roaster-scope/artisan#1011] opened 2022-11-19 03:59 UTC
**Describe the bug**
After upgrading to 2.8, I am unable to save a pdf graphic.  (File > Save Graphic > pdf.
I am able to Save Graphic if I select jpg.
I have tried loading .alog files that I created in 2.6 or 2.8.

**To Reproduce**
File > Save Graphic > pdf
No file is created
But if you
File > Save Graphic > jpg
A file is created

**Expected behavior**
In 2.6, once select File > Save Graphic > pdf, you should get a pdf file
in 2.8, no pdf file is created

**Screenshots**
n/a

**Setup (please complete the following information):**
 - Artisan Version 2.8.0  
 - Artisan Build (682bdaf):
 - Version Python 3.10.4, Qt 6.4.0, PyQt 6.4.0, Matplotlib 3.6.1, NumPy 1.23.4, SciPy 1.9.2, pymodbus 2.5.3 (1.12.20220912), Yoctopuce 1.10.51266 (1.10.51266) 
 - Platform Windows, Windows 10 Home, version 21H2, osbuild 19044.2251:
 - Connected devices Normally Masteck, butalsoif not connected:

**Additional context**

Please attach your current Artisan settings file (as exported via menu Help >> Save Settings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._
[artisan-settings.aset.txt](https://github.com/artisan-roaster-scope/artisan/files/10046009/artisan-settings.aset.txt)
[22-11-18_1555(#78).alog.txt](https://github.com/artisan-roaster-sco
[22-11-14_1020(#76).alog.txt](https://github.com/artisan-roaster-scope/artisan/files/10046011/22-11-14_1020.76.alog.txt)
pe/artisan/files/10046010/22-11-18_1555.78.alog.txt)

**Comment by roasterdave** [comment] 2022-11-19 06:59
Thanks for the detailed report.  We really appreciate it.  This problem is due to a regression in the build process.  It is now fixed in the continuous builds available here https://github.com/artisan-roaster-scope/artisan/releases/tag/continuous

**Closed** 2022-11-19 07:00 UTC
