### ISSUE TITLE
unhandled exception occurred

### ISSUE THREAD

**Issue by bigl00z3** [artisan-roaster-scope/artisan#299] opened 2019-01-22 12:28 UTC
## Expected Behavior
Selecting coffee in Roast Properties

## Actual Behavior

Error Popup when selecting coffee in Roast Properties (A+ version)

Error Message:

_

> An unhandled exception occurred. Please report the problem on Github:
> https://github.com/artisan-roaster-scope/artisan/issues
> When reporting this issue, please include your settings file (export 
> via menu Help >> Save Settings) and the details below.
> 
> An entry has been written to the error log (menu Help >> Error).
> 
> Version: 1.6.0, revision: 7b160ba
> 2019-01-19, 15:07:28
> --------------------------------------------------------------------------------
> <class 'KeyError'>: 
> 'origin'
> 
> 
> 
> An unhandled exception occurred. Please report the problem on Github:
> https://github.com/artisan-roaster-scope/artisan/issues
> When reporting this issue, please include your settings file (export 
> via menu Help >> Save Settings) and the details below.
> 
> An entry has been written to the error log (menu Help >> Error).
> 
> Version: 1.6.0, revision: 7b160ba
> 2019-01-19, 15:07:28
> --------------------------------------------------------------------------------
> <class 'KeyError'>: 
> 'origin'

_

## Steps to Reproduce the Problem

  1. Error only happened once but as requested in the error message. reporting it.
  2. 
  3. 

## Specifications

  - Artisan Version: 1.6.0
  - Artisan Build (number in brackets shown in the about box): 7b160ba
  - Platform (Mac/Windows/Linux + OS version): Raspbian
  - Connected devices or roasting machine: Phidgets (1048, HUB0000, HUM1000, PRE1000, 1135)

  
Please attach your current Artisan settings file (as exported via menu Help >> Save Setings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

[artisan-settings Pi A+ 1.6.0.aset.txt](https://github.com/artisan-roaster-scope/artisan/files/2782722/artisan-settings.Pi.A%2B.1.6.0.aset.txt)

**Comment by MAKOMO** [comment] 2019-01-22 16:06
Thanks Nico for reporting. This issue was discovered before and is caused by a "plus" Coffee that does not specify an origin. Its already fixed by commit c75b8672c10516ff2022106a50dd750c599e18ad. I'll prepare new builds that include this fix and hopefully fix for your other bug report (which is way more tricky).

**Closed by MAKOMO** 2019-01-22 16:06 UTC
