### ISSUE TITLE
Linux GUI - highlighting problem

### ISSUE THREAD

**Issue by RickGroszkiewicz** [artisan-roaster-scope/artisan#122] opened 2017-06-25 00:39 UTC
I am running artisan 1.1.0 under Linux Mint. Under Tools / Extras / UI I have selected Fusion. The same thing happens if I select Windows.

When using File / Open (such as for loading profiles or alarms), the selected item is not highlighted. Instead, I see a blank line in the list of available items. Just curious if this is the intended result.
![artisan gui highlight problem from 2017-06-17 09-58-04](https://user-images.githubusercontent.com/25457554/27512831-2485aa92-591d-11e7-9588-9cdf9dca4fd0.png)

**Comment by MAKOMO** [comment] 2017-06-25 09:25
Dear Rick, thanks for reporting. This must be caused by an issue in the underlying GUI toolkit Qt. I do not have much influence on this. I close this as it should resolve itself once I update to a newer build setup for Linux which will be based on a newer Linux glibc, Python3 and the latest Qt toolkit. Thanks for reporting

**Closed by MAKOMO** 2017-06-25 09:25 UTC
