### ISSUE TITLE
Changes not discarded when CANCEL (versus OK) is selected/clicked

### ISSUE THREAD

**Issue by DennieSch** [artisan-roaster-scope/artisan#409] opened 2019-10-19 00:28 UTC
## Expected Behavior
Changes to values, check boxes, etc. are discarded when CANCEL (versus OK) is selected/clicked

## Actual Behavior
Changes are retained and not discarded

## Steps to Reproduce the Problem

  1. Config/Curves/Filters
  2. Change any value or any check box (except MINs or MAXs)
  3. Click CANCEL
  4. Re-open window and notice the change(s) were retained and not discarded
 
Note:
- 'Config/Curves/Filters'; this anomaly does NOT appear to occur with the two MIN and two MAX data boxes.
- Some Elements on other Tabs of 'Curves' also exhibits this anomaly.
- Some Elements on other Menu items also exhibits this anomaly.
- I have not reviewed all Menus, Tabs, etc. for is anomaly.

## Specifications

[artisan-settings.zip](https://github.com/artisan-roaster-scope/artisan/files/3746030/artisan-settings.zip)

-version = 2.0.1 (adb4c2da)
Architecture = ('64bit', 'WindowsPE')
Machine = AMD64
Platform name = Windows-10-10.0.18362-SP0
Processor = Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
Python Branch = tags/v3.7.4
Python Build = ('tags/v3.7.4:e09359112e', 'Jul 8 2019 20:34:20')
Python Compiler = MSC v.1916 64 bit (AMD64)
Python Implementation = CPython
Python Revision = e09359112e
Python version = 3.7.4
Release = 10
System = Windows
Version = 10.0.18362
Win32 = ('10', '10.0.18362', 'SP0', '')

  - Connected devices or roasting machine: none
  
Please attach your current Artisan settings file (as exported via menu Help >> Save Setings as *.aset) file.
Please attach any relevant Artisan *.alog profiles.

_Note that you need either add a `.txt` extension or zip the files before uploading. Otherwise you will receive a "Not a supported file type" error on uploading._

**Comment by MAKOMO** [comment] 2019-10-23 10:28
Resolved by Commit b68ce1a88059dc6b0cf0550280d14f8bb321c2e5. Initial none of the Artisan dialogs had a Cancel button. As they were added, not all of the old dialog behavior was correctly updated (also due to internal complications caused by the original design). There might be more places where this comes to the surface again.... Thanks for reporting.

**Closed by MAKOMO** 2019-10-23 10:28 UTC
